<a href="https://colab.research.google.com/github/daleyprabhakar/keras/blob/master/Simple_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
**ANN**
```



In [ ]:
!pip install keras

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [8]:
docs = ['go india',
'india india',
'hip hip hurray',
'jeetega bhai jeetega india jeetega',
'bharat mata ki jai',
'kohli kohli',
'sachin sachin',
'dhoni dhoni',
'modi ji ki jai',
'inquilab zindabad']

In [10]:
tokenizer.fit_on_texts(docs)

In [11]:
len(tokenizer.word_index)
print(tokenizer.word_index)

{'india': 1, 'jeetega': 2, 'hip': 3, 'ki': 4, 'jai': 5, 'kohli': 6, 'sachin': 7, 'dhoni': 8, 'go': 9, 'hurray': 10, 'bhai': 11, 'bharat': 12, 'mata': 13, 'modi': 14, 'ji': 15, 'inquilab': 16, 'zindabad': 17}


In [13]:
print(tokenizer.word_counts)

OrderedDict([('go', 1), ('india', 4), ('hip', 2), ('hurray', 1), ('jeetega', 3), ('bhai', 1), ('bharat', 1), ('mata', 1), ('ki', 2), ('jai', 2), ('kohli', 2), ('sachin', 2), ('dhoni', 2), ('modi', 1), ('ji', 1), ('inquilab', 1), ('zindabad', 1)])


In [12]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [14]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [15]:
model = Sequential()
vocab_size = len(tokenizer.word_index) + 1
model.add(Embedding(vocab_size,output_dim=2,input_length=5))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.compile('adam','accuracy')

In [17]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 255ms/step
[[[-0.0377064   0.04730761]
  [ 0.00325807 -0.01244907]
  [-0.01704124 -0.03062832]
  [-0.01704124 -0.03062832]
  [-0.01704124 -0.03062832]]

 [[ 0.00325807 -0.01244907]
  [ 0.00325807 -0.01244907]
  [-0.01704124 -0.03062832]
  [-0.01704124 -0.03062832]
  [-0.01704124 -0.03062832]]

 [[ 0.03640863 -0.04258214]
  [ 0.03640863 -0.04258214]
  [ 0.04780037  0.00038272]
  [-0.01704124 -0.03062832]
  [-0.01704124 -0.03062832]]

 [[-0.0362289   0.03794144]
  [ 0.01361955 -0.0265797 ]
  [-0.0362289   0.03794144]
  [ 0.00325807 -0.01244907]
  [-0.0362289   0.03794144]]

 [[-0.02492085  0.03728434]
  [-0.03795135  0.03375299]
  [-0.04198145  0.02960781]
  [-0.02022674 -0.04470171]
  [-0.01704124 -0.03062832]]

 [[-0.00650166 -0.00771432]
  [-0.00650166 -0.00771432]
  [-0.01704124 -0.03062832]
  [-0.01704124 -0.03062832]
  [-0.01704124 -0.03062832]]

 [[-0.00982308 -0.03597149]
  [-0.00982308 -0.03597149]
  [-0.01704124 -0.03062832]
  [-0.01704124 -0.0306283



```
** Simple RNN for docs **
```



In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

# Sample dataset
docs = ['go india',
'india india',
'hip hip hurray',
'jeetega bhai jeetega india jeetega',
'bharat mata ki jai',
'kohli kohli',
'sachin sachin',
'dhoni dhoni',
'modi ji ki jai',
'inquilab zindabad']

# Labels (for binary classification: 0 = neutral, 1 = positive sentiment)
labels = np.array([1, 1, 1, 1, 1, 0, 0, 0, 1, 1])

# Tokenization
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
sequences = tokenizer.texts_to_sequences(docs)

# Padding
sequences = pad_sequences(sequences, padding='post')

# Define model
model = Sequential()
model.add(Embedding(input_dim=18, output_dim=2, input_length=5)) # Embedding layer
model.add(SimpleRNN(32)) # RNN to process sequences
model.add(Dense(1, activation='sigmoid')) # Output layer for binary classification

# Compile model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train model
model.fit(sequences, labels, epochs=5, batch_size=2)

# Predict sentiment for the input sequences
predictions = model.predict(sequences)
print("Predictions:", predictions)


# Convert probabilities to binary outputs (0 or 1)
binary_predictions = (predictions > 0.5).astype(int) # Threshold at 0.5
print("Binary Predictions:", binary_predictions.flatten()) # Flatten for better display

Epoch 1/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6778 - loss: 0.6910
Epoch 2/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6778 - loss: 0.6795 
Epoch 3/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7611 - loss: 0.6622 
Epoch 4/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6292 - loss: 0.6662 
Epoch 5/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6778 - loss: 0.6488 
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step
Predictions: [[0.58454984]
 [0.58084816]
 [0.58181965]
 [0.5837253 ]
 [0.58097655]
 [0.57282376]
 [0.57788914]
 [0.5775029 ]
 [0.5979062 ]
 [0.58212155]]
Binary Predictions: [1 1 1 1 1 1 1 1 1 1]


** Using Simple RNN with IMDB data **

In [1]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding
import numpy as np

# Load the IMDB dataset
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)  # Limit vocabulary to 10,000 words

# Pad sequences to a fixed length (e.g., 500)
maxlen = 500
X_train = pad_sequences(X_train, padding='post', maxlen=maxlen)
X_test = pad_sequences(X_test, padding='post', maxlen=maxlen)

# Print shapes and vocabulary size
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
vocab_size = max(max(sequence) for sequence in X_train) + 1
print("Vocabulary size:", vocab_size)

# Define the model
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=50, input_length=maxlen))  # Set input_length to maxlen
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

# Print model summary
print(model.summary())

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

(25000, 500) (25000, 500) (25000,) (25000,)
Vocabulary size: 10000


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None
Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 118s 147ms/step - accuracy: 0.4965 - loss: 0.6950 - val_accuracy: 0.5032 - val_loss: 0.6931
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 115s 147ms/step - accuracy: 0.5029 - loss: 0.6933 - val_accuracy: 0.5013 - val_loss: 0.6935
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 151s 159ms/step - accuracy: 0.5128 - loss: 0.6915 - val_accuracy: 0.5021 - val_loss: 0.6957
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 154s 174ms/step - accuracy: 0.5294 - loss: 0.6811 - val_accuracy: 0.5066 - val_loss: 0.6936
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 122s 148ms/step - accuracy: 0.5258 - loss: 0.6717 - val_accuracy: 0.5080 - val_loss: 0.6982


In [3]:
predictions = (model.predict(X_test) > 0.5).astype(int)
print(predictions)

782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 27ms/step
[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
